### PR TITLE
Initialise flag for all bulbs

### PR DESCRIPTION
**Pull request by Hate-Usernames**
Missing line from previous PR -- sorry!

### CODE REVIEW

**Comment by ggravlingen** [comment]
What does the line do?

**Comment by ggravlingen** [comment]
Please also bump version by 0.0.1 as this is a bug fix?

**Comment by Hate-Usernames** [comment]
With this fix it's now safe to call `light.light_control.can_combine_commands` to see if it is safe to combine changing the colour and brightness in a single API call, e.g.:
```
if light.light_control.can_combine_commands:
    api(color_command + dimmer_command)
else:
    api(color_command)
    api(dimmer_command)
```

**Comment by ggravlingen** [comment]
@Hate-Usernames: I've pushed this to pypi now. Thanks for your contribution!

**Pull request merged**
