### PR TITLE
Psk handling clarification

### PR DESCRIPTION
**Pull request by Lakitna**
#133

### CODE REVIEW

**Comment by Lakitna** [comment]
Interactive mode still needs to be changed to the new KEY input method. Readme could use some love too.

@ggsubs I'd like your opinion :)

**Comment by ggravlingen** [comment]
Nice, thank you! Do you want to await comments from @ggsubs before I merge?

**Comment by Lakitna** [comment]
I'd like to change interactive mode too before merging. That'll give @ggsubs time to comment as well.

**Comment by ggravlingen** [comment]
@Lakitna OK!

**Comment by Lakitna** [comment]
Any change suggestions? If not it's ready to merge.

**Comment by ggravlingen** [comment]
Thank you!

**Pull request merged**
