### PR TITLE
Resolve issue with libcoap API

### PR DESCRIPTION
**Pull request by ggravlingen**
This is a solution proposed by @rudyvan

### CODE REVIEW

**Comment by ggravlingen** [comment]
@lwis can the error thrown by Travis be accepted?

It's the except: pass lines (from device.py) that fail and some Google-fu tells me it's advised to not use this syntax?

````
    def set_predefined_color(self, colorname, *, index=0):
        try:
            color = COLORS[colorname.lower().replace(" ", "_")]
        except:
            pass
        else:
            return self.set_hex_color(color, index=index)
````

**Comment by lwis** [comment]
Hmm, that needs fixing. We must be expecting some builtin exception to be thrown there. Catch all isn't good practice.

**Comment by ggravlingen** [comment]
@lwis my thoughts too as Travis passed this in the previous PR. Suggestion: let this through (as it's already a part of master branch) and raise a bug to fix it?

**Comment by ggravlingen** [comment]
Getting this error when implementing the suggested fix. Putting it here for documentation and am currently looking into it.

```
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.0.129 get ['status']
DEBUG:pytradfri.api.libcoap_api:Received: {}
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.0.129 get ['15001']
DEBUG:pytradfri.api.libcoap_api:Received: [65541,65538,65536,65537,65540,65539,65542]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/patrik/Documents/pytradfri/pytradfri/__main__.py", line 22, in <module>
    devices = api(*devices_commands)
TypeError: request() takes 1 positional argument but 7 were given
```

**Comment by rudyvan** [comment]
You just have to remove the asterix and then it worked, apologies i should have mentioned it.
devices=api(devices_commands)
Sorry, traveling now and cannot help further.

**Pull request merged**
