### PR TITLE
Resolve issue with libcoap API.

### PR DESCRIPTION
**Pull request by rudyvan**

### CODE REVIEW

**Comment by ggravlingen** [comment]
@rudyvan Can you please rebase with master (to thus remove the addition to device.py as it's unnecessary to make that change again.)

@lwis may I please ask you to verity the change to libcoap_api.py?

**Comment by rudyvan** [comment]
i cloned, rebased, merged and pushed in a fresh directory.
now i should request a pull (yet again?)

**Comment by lwis** [comment]
Change to libcoap is correct, and resolves #72. Not sure how I missed that!

**Comment by ggravlingen** [comment]
@rudyvan I think it'll suffice if you execute the following command in your repo before you commit and push:
```
git rm --cached device.py
```
That should also take care of the failing Travis build.

**Comment by ggravlingen** [comment]
@lwis thanks for looking into the issue!

**Comment by rudyvan** [comment]
did the rm cashed and pushed followed by reissueing a pull request.
I hope it now passes.

**Comment by ggravlingen** [comment]
Looks like that wasn't good advise on my side. I misinterpreted what I read and though only the libcoap_pi.py-file would remain as part of the PR. :disappointed:

**Pull request closed without merging**
