### PR TITLE
Add a "Reviewed by Hound" badge

### PR DESCRIPTION
**Pull request by salbertson**
screenshot 2019-01-08 18 50 32

### CODE REVIEW

**Comment by ggravlingen** [comment]
Thanks for the PR! Am I correct in that you are the author of Hound?

**Comment by salbertson** [comment]
No problem @ggravlingen.

> Am I correct in that you are the author of Hound?

Yep, I am.

**Comment by ggravlingen** [comment]
It's a great tool to use as a maintainer, thank you very much!

**Comment by salbertson** [comment]
@ggravlingen I'm glad it helps!

**Pull request merged**
